%% docs/dag.mmd  
gitGraph  
  commit id: "a1b2c" type: NORMAL  
  commit id: "d3e4f" type: NORMAL  
  branch feature  
  commit id: "g5h6i" type: NORMAL  
  checkout main  
  commit id: "j7k8l" type: NORMAL  
  merge feature id: "m9n0o"  