name: Draft Release
on:
  push:
    tags:
      - 'v*'
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
